gems:
  - jemoji

theme: jekyll-theme-cayman
title: Bobchain Ltd.
description: The disruptive company that [makes the World a better place](https://www.youtube.com/watch?v=J-GVd_HLlps) by revolutionizing everything
